ubervisor-all docs and install
- install ubervisor-all with `make install`.
- make ubervisor-all a bit more helpful.
- add manpage.
- add -v and -V flags to ubervisor to print only the version header.

diff --git a/ubervisor-all b/ubervisor-all
--- a/ubervisor-all
+++ b/ubervisor-all
@@ -3,6 +3,19 @@ if [ -x ./ubervisor ]; then
 	UBER=./ubervisor
 else
 	UBER=`which ubervisor`
+	if [ -z "$UBER" ]; then
+		echo "Can't find ubervisor executable"
+		exit 1
+	fi
+fi
+
+if [ -z "$1" ]; then
+	echo
+	$UBER -v
+	echo
+	echo "Usage: $0 <command> [args ...]"
+	echo
+	exit 1
 fi
 
 GROUPS=$($UBER list)
